### ISSUE TITLE
Add missing components to Storybook

### ISSUE THREAD

**Issue by d3v0ps** [d3v0ps/angular-nest-starter#2]
We should add missing component examples to storybook:

- [x] Dialog #4
- [x] FAB #5
- [x] Form Field #6
- [x] Icon / Icon Button #7
- [x] Image List #8
- [x] Linear Progress #9
- [x] List #10
- [x] Menu / Menu Surface #11
- [x] Radio Buttons #12
- [x] Slider #13
- [x] Snackbar #14
- [x] Switch #15
- [x] Tabs #3
- [x] Textarea #16
- [x] Text Field #17
- [x] Top App Bar #18
